<?php
if ($_GET['advertiser']!=''){
	header("Content-type: text/xml");
	require_once('../../booking/init.php');

	//$_GET['property_id']='22';
	// if ($_GET['property_id']){ }
	 //$link= new getQueries();
	 //$bookings=$link->availability_flipkey($_GET['property_id']);
	 $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
	$base_url="$protocol://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER["REQUEST_URI"]);
	echo '<?xml version="1.0" encoding="UTF-8"?>';
	echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
	echo '<advertiserLodgingRateContentIndex>';
		echo '<documentVersion>4.1</documentVersion>';
		echo '<advertiser>';
			echo '<assignedId>'.$_GET['advertiser'].'</assignedId>';
			echo '<lodgingRateContentIndexEntry>';
				echo '<listingExternalId>'.$_GET['advertiser'].'</listingExternalId>';
				echo '<unitExternalId>'.$_GET['advertiser'].'</unitExternalId>';
				echo '<lastUpdatedDate>'.gmdate("Y-m-d\TH:i:s\Z").'</lastUpdatedDate>';
				echo '<lodgingRateContentUrl>'.$base_url.'/rates.php?id='.$_GET['advertiser'].'</lodgingRateContentUrl>';
			echo '</lodgingRateContentIndexEntry>';
		echo '</advertiser>';
	echo '</advertiserLodgingRateContentIndex>';
}