<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
echo '<advertisersContentIndex>';
	echo '<documentVersion>4.1</documentVersion>';
	echo '<advertiserIndexEntry>';
		echo '<advertiserAssignedId>advertiser_1</advertiserAssignedId>';
		echo '<advertiserName>Advertiser Name 1</advertiserName>';
		echo '<advertiserListingContentIndexUrl>http://www.site.com/ha/listingsIndex?advertiser=1</advertiserListingContentIndexUrl>';
		echo '<advertiserLodgingConfigurationContentIndexUrl>http://www.site.com/ha/configIndex?advertiser=1</advertiserLodgingConfigurationContentIndexUrl>';
		echo '<advertiserLodgingRateContentIndexUrl>http://www.site.com/ha/lodgingRatesIndex?advertiser=1</advertiserLodgingRateContentIndexUrl>';
		echo '<advertiserUnitAvailabilityContentIndexUrl>http://www.site.com/ha/availabilityIndex?advertiser=1</advertiserUnitAvailabilityContentIndexUrl>';
	echo '</advertiserIndexEntry>';
	echo '<advertiserIndexEntry>';
		echo '<advertiserAssignedId>advertiser_2</advertiserAssignedId>';
		echo '<advertiserName>Advertiser Name 2</advertiserName>';
		echo '<advertiserListingContentIndexUrl>http://www.site.com/ha/listingsIndex?advertiser=2</advertiserListingContentIndexUrl>';
		echo '<advertiserLodgingConfigurationContentIndexUrl>http://www.site.com/ha/configIndex?advertiser=2</advertiserLodgingConfigurationContentIndexUrl>';
		echo '<advertiserLodgingRateContentIndexUrl>http://www.site.com/ha/lodgingRatesIndex?advertiser=2</advertiserLodgingRateContentIndexUrl>';
		echo '<advertiserUnitAvailabilityContentIndexUrl>http://www.site.com/ha/availabilityIndex?advertiser=2</advertiserUnitAvailabilityContentIndexUrl>';
	echo '</advertiserIndexEntry>';
	echo '<advertiserIndexEntry>';
		echo '<advertiserAssignedId>advertiser_3</advertiserAssignedId>';
		echo '<advertiserName>Advertiser Name 3</advertiserName>';
		echo '<advertiserListingContentIndexUrl>http://www.site.com/ha/listingsIndex?advertiser=3</advertiserListingContentIndexUrl>';
		echo '<advertiserLodgingConfigurationContentIndexUrl>http://www.site.com/ha/configIndex?advertiser=3</advertiserLodgingConfigurationContentIndexUrl>';
		echo '<advertiserLodgingRateContentIndexUrl>http://www.site.com/ha/lodgingRatesIndex?advertiser=3</advertiserLodgingRateContentIndexUrl>';
		echo '<advertiserUnitAvailabilityContentIndexUrl>http://www.site.com/ha/availabilityIndex?advertiser=3</advertiserUnitAvailabilityContentIndexUrl>';
	echo '</advertiserIndexEntry>';
echo '</advertisersContentIndex>';