<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
echo '<advertiserUnitAvailabilityContentIndex>';
	echo '<documentVersion>4.1</documentVersion>';
	echo '<advertiser>';
		echo '<assignedId>advertiser_1</assignedId>';
		echo '<unitAvailabilityContentIndexEntry>';
			echo '<listingExternalId>501</listingExternalId>';
			echo '<unitExternalId>501a</unitExternalId>';
			echo '<lastUpdatedDate>2016-09-02T10:23:35Z</lastUpdatedDate>';
			echo '<unitAvailabilityContentUrl>http://www.site.com/ha/availability?id=501a</unitAvailabilityContentUrl>';
		echo '</unitAvailabilityContentIndexEntry>';
		echo '<unitAvailabilityContentIndexEntry>';
			echo '<listingExternalId>501</listingExternalId>';
			echo '<unitExternalId>501b</unitExternalId>';
			echo '<lastUpdatedDate>2016-09-03T13:30:35Z</lastUpdatedDate>';
			echo '<unitAvailabilityContentUrl>http://www.site.com/ha/availability?id=501b</unitAvailabilityContentUrl>';
		echo '</unitAvailabilityContentIndexEntry>';
		echo '<unitAvailabilityContentIndexEntry>';
			echo '<listingExternalId>502</listingExternalId>';
			echo '<unitExternalId>502a</unitExternalId>';
			echo '<lastUpdatedDate>2016-09-02T18:00:35Z</lastUpdatedDate>';
			echo '<unitAvailabilityContentUrl>http://www.site.com/ha/availability?id=502a</unitAvailabilityContentUrl>';
		echo '</unitAvailabilityContentIndexEntry>';
	echo '</advertiser>';
echo '</advertiserUnitAvailabilityContentIndex>';