<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
echo '<advertiserLodgingConfigurationContentIndex>';
	echo '<documentVersion>4.1</documentVersion>';
	echo '<advertiser>';
		echo '<assignedId>advertiser_1</assignedId>';
		echo '<lodgingConfigurationDefaults>';
			echo '<acceptedPaymentForms>';
				echo '<paymentCardDescriptor>';
					echo '<paymentFormType>CARD</paymentFormType>';
					echo '<cardCode>MASTERCARD</cardCode>';
					echo '<cardType>CREDIT</cardType>';
				echo '</paymentCardDescriptor>';
				echo '<paymentCardDescriptor>';
					echo '<paymentFormType>CARD</paymentFormType>';
					echo '<cardCode>VISA</cardCode>';
					echo '<cardType>CREDIT</cardType>';
				echo '</paymentCardDescriptor>';
				echo '<paymentCardDescriptor>';
					echo '<paymentFormType>CARD</paymentFormType>';
					echo '<cardCode>VISA_ELECTRON</cardCode>';
					echo '<cardType>DEBIT</cardType>';
				echo '</paymentCardDescriptor>';
			echo '</acceptedPaymentForms>';
			echo '<bookingPolicy>';
				echo '<policy>INSTANT</policy>';
			echo '</bookingPolicy>';
			echo '<cancellationPolicy>';
				echo '<policy>NO_REFUND</policy>';
			echo '</cancellationPolicy>';
			echo '<checkInTime>Flexible</checkInTime>';
			echo '<checkOutTime>Flexible</checkOutTime>';
			echo '<childrenAllowedRule>';
				echo '<allowed>true</allowed>';
			echo '</childrenAllowedRule>';
			echo '<eventsAllowedRule>';
				echo '<allowed>true</allowed>';
			echo '</eventsAllowedRule>';
			echo '<lastUpdatedDate>2017-03-10T03:17:40+01:00</lastUpdatedDate>';
			echo '<locale>en</locale>';
			echo '<maximumOccupancyRule>';
				echo '<adults>99</adults>';
				echo '<guests>99</guests>';
			echo '</maximumOccupancyRule>';
			echo '<minimumAgeRule>';
				echo '<age>18</age>';
			echo '</minimumAgeRule>';
			echo '<petsAllowedRule>';
				echo '<allowed>true</allowed>';
			echo '</petsAllowedRule>';
			echo '<pricingPolicy>';
				echo '<policy>GUARANTEED</policy>';
			echo '</pricingPolicy>';
			echo '<rentalAgreementFile>';
				echo '<rentalAgreementPdfUrl>http://site.com/en/info/terms/</rentalAgreementPdfUrl>';
			echo '</rentalAgreementFile>';
			echo '<smokingAllowedRule>';
				echo '<allowed>true</allowed>';
			echo '</smokingAllowedRule>';
		echo '</lodgingConfigurationDefaults>';
		echo '<lodgingConfigurationContentIndexEntry>';
			echo '<listingExternalId>501</listingExternalId>';
			echo '<unitExternalId>501a</unitExternalId>';
			echo '<lastUpdatedDate>2017-03-09T21:32:50+01:00</lastUpdatedDate>';
			echo '<lodgingConfigurationContentUrl>http://www.site.com/ha/lodgingConfig?id=501a</lodgingConfigurationContentUrl>';
		echo '</lodgingConfigurationContentIndexEntry>';
		echo '<lodgingConfigurationContentIndexEntry>';
			echo '<listingExternalId>501</listingExternalId>';
			echo '<unitExternalId>501b</unitExternalId>';
			echo '<lastUpdatedDate>2017-03-09T21:32:50+01:00</lastUpdatedDate>';
			echo '<lodgingConfigurationContentUrl>http://www.site.com/ha/lodgingConfig?id=501b</lodgingConfigurationContentUrl>';
		echo '</lodgingConfigurationContentIndexEntry>';
		echo '<lodgingConfigurationContentIndexEntry>';
			echo '<listingExternalId>502</listingExternalId>';
			echo '<unitExternalId>502</unitExternalId>';
			echo '<lastUpdatedDate>2017-03-09T21:32:50+01:00</lastUpdatedDate>';
			echo '<lodgingConfigurationContentUrl>http://www.site.com/ha/lodgingConfig?id=502</lodgingConfigurationContentUrl>';
		echo '</lodgingConfigurationContentIndexEntry>';
	echo '</advertiser>';
echo '</advertiserLodgingConfigurationContentIndex>';