<?php
if ($_GET['advertiser']!=''){
header("Content-type: text/xml");
require_once('../../booking/init.php');

 
	 //$link= new getQueries();
	 //$bookings=$link->availability_flipkey($_GET['property_id']);
	 
	 $link= new getQueries();
	 $villas = $link->showTable_restrinted("villas", "able_r=1 AND `wish_referal`='0' AND `vonline`='0'" ,'id');
	 
	$protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
	$base_url="$protocol://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER["REQUEST_URI"]);
	 
	echo '<?xml version="1.0" encoding="UTF-8"?>';
	echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
	echo '<advertiserListingContentIndex>';
		echo '<documentVersion>4.1</documentVersion>';
		echo '<advertiser>';
			echo '<assignedId>'.$_GET['advertiser'].'</assignedId>';
		if($villas){
			foreach($villas AS $k){
				echo '<listingContentIndexEntry>';
					echo '<listingExternalId>'.$k['id'].'</listingExternalId>';
					echo '<active>true</active>';
					echo '<lastUpdatedDate>'.gmdate("Y-m-d\TH:i:s\Z").'</lastUpdatedDate>';
					echo '<listingUrl>'.$base_url.'/listing.php?id='.$k['id'].'</listingUrl>';
				echo '</listingContentIndexEntry>';
			}
		}
		echo '</advertiser>';
	echo '</advertiserListingContentIndex>';
}