<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 //if ($_GET['property_id']){ }
 $link= new getQueries();
 //$bookings=$link->availability_flipkey($_GET['property_id']);
  $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
	$base_url="$protocol://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER["REQUEST_URI"]);
	$villa=$link->show_id($table='villas', $id=$_GET['id']);
	 $v=$villa[0];
	
echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
echo '<lodgingConfigurationContent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:'.$base_url.'/xml/HA-XML-Listings-4.1.xsd">';
	echo '<listingExternalId>'.$_GET['id'].'</listingExternalId>';
	echo '<unitExternalId>'.$_GET['id'].'</unitExternalId>';
	echo '<lodgingConfiguration>';
		echo '<acceptedPaymentForms>';
			/*echo '<paymentCardDescriptor>';
				echo '<paymentFormType>CARD</paymentFormType>';
				echo '<cardCode>AMEX</cardCode>';
				echo '<cardType>CREDIT</cardType>';
			echo '</paymentCardDescriptor>';*/
			echo '<paymentCardDescriptor>';
				echo '<paymentFormType>CARD</paymentFormType>';
				echo '<cardCode>MASTERCARD</cardCode>';
				echo '<cardType>CREDIT</cardType>';
			echo '</paymentCardDescriptor>';
			echo '<paymentCardDescriptor>';
				echo '<paymentFormType>CARD</paymentFormType>';
				echo '<cardCode>VISA</cardCode>';
				echo '<cardType>CREDIT</cardType>';
			echo '</paymentCardDescriptor>';
		echo '</acceptedPaymentForms>';
		echo '<bookingPolicy>';
			echo '<policy>INSTANT</policy>';
		echo '</bookingPolicy>';
		echo '<cancellationPolicy>';
			echo '<policy>Firm</policy>';
		echo '</cancellationPolicy>';
		echo '<checkInTime>15:00</checkInTime>';
		echo '<checkOutTime>12:00</checkOutTime>';
		echo '<childrenAllowedRule>';
			echo '<allowed>true</allowed>';
		echo '</childrenAllowedRule>';
		echo '<eventsAllowedRule>';
			echo '<allowed>false</allowed>';
		echo '</eventsAllowedRule>';
		echo '<maximumOccupancyRule>';
			echo '<adults>'.$v['capacity'].'</adults>';
			echo '<guests>'.$v['capacity'].'</guests>';
		echo '</maximumOccupancyRule>';
		echo '<petsAllowedRule>';
			echo '<allowed>false</allowed>';
		echo '</petsAllowedRule>';
		echo '<smokingAllowedRule>';
			echo '<allowed>false</allowed>';
		echo '</smokingAllowedRule>';
	echo '</lodgingConfiguration>';
echo '</lodgingConfigurationContent>';