<?php
if ($_GET['advertiser']!=''){
	header("Content-type: text/xml");
	require_once('../../booking/init.php');
	
	$protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
	$base_url="$protocol://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER["REQUEST_URI"]);

	//$_GET['property_id']='22';
	 if ($_GET['property_id']){ }
	 $link= new getQueries();
	 $bookings=$link->availability_flipkey($_GET['property_id']);
	 
	echo '<?xml version="1.0" encoding="UTF-8"?>';
	echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
	echo '<advertiserUnitAvailabilityContentIndex>';
		echo '<documentVersion>4.1</documentVersion>';
		echo '<advertiser>';
			echo '<assignedId>'.$_GET['advertiser'].'</assignedId>';
			echo '<unitAvailabilityContentIndexEntry>';
				echo '<listingExternalId>'.$_GET['advertiser'].'</listingExternalId>';
				echo '<unitExternalId>'.$_GET['advertiser'].'</unitExternalId>';
				echo '<lastUpdatedDate>'.gmdate("Y-m-d\TH:i:s\Z").'</lastUpdatedDate>';
				echo '<unitAvailabilityContentUrl>'.$base_url.'/availability.php?id='.$_GET['advertiser'].'</unitAvailabilityContentUrl>';
			echo '</unitAvailabilityContentIndexEntry>';
		echo '</advertiser>';
	echo '</advertiserUnitAvailabilityContentIndex>';
}