<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
echo '<unitAvailabilityContent>';
	echo '<listingExternalId>501</listingExternalId>';
	echo '<unitExternalId>501a</unitExternalId>';
	echo '<unitAvailability>';
		echo '<availabilityDefault>Y</availabilityDefault>';
		echo '<availableUnitCountDefault>3</availableUnitCountDefault>';
		echo '<changeOverDefault>X</changeOverDefault>';
		echo '<dateRange>';
			echo '<beginDate>2017-08-01</beginDate>';
			echo '<endDate>2017-08-31</endDate>';
		echo '</dateRange>';
		echo '<maxStayDefault>28</maxStayDefault>';
		echo '<minPriorNotifyDefault>14</minPriorNotifyDefault>';
		echo '<minStayDefault>3</minStayDefault>';
		echo '<stayIncrementDefault>D</stayIncrementDefault>';
		echo '<unitAvailabilityConfiguration>';
			echo '<availability>NNYYYYYYYYNNNNNNNYYYYYYYYYYYYYY</availability>';
			echo '<availableUnitCount>0,0,1,2,2,3,3,3,3,3,0,0,0,0,0,0,0,1,1,1,2,2,2,2,3,3,3,3,3,1,1</availableUnitCount>';
			echo '<changeOver>CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC</changeOver>';
			echo '<maxStay>28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28</maxStay>';
			echo '<minPriorNotify>14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14</minPriorNotify>';
			echo '<minStay>3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3</minStay>';
			echo '<stayIncrement>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</stayIncrement>';
		echo '</unitAvailabilityConfiguration>';
	echo '</unitAvailability>';
echo '</unitAvailabilityContent>';