<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<listing>';
	echo '<externalId>501</externalId>';
	echo '<active>true</active>';
	echo '<adContent>';
		echo '<accommodationsSummary>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>House, 4 Bedrooms, 4 Baths, (Sleeps 10)</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</accommodationsSummary>';
		echo '<description>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>This beautiful historic home is over 100 years old with an absolutely stunning view of the ocean.</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</description>';
		echo '<headline>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>This Home is simply Beautiful!</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</headline>';
		echo '<ownerListingStory>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>This home was purchased by our grandfather in 1963.</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</ownerListingStory>';
		echo '<propertyName>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>Oceanside Estate</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</propertyName>';
		echo '<uniqueBenefits>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>Minutes from the ocean!</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</uniqueBenefits>';
		echo '<whyPurchased>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>To provide a relaxing summer resort.</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</whyPurchased>';
		echo '<yearPurchased>1963</yearPurchased>';
	echo '</adContent>';
	echo '<featureValues>';
		echo '<featureValue>';
			echo '<count>1</count>';
			echo '<listingFeatureName>LOCATION_TYPE_BEACH</listingFeatureName>';
		echo '</featureValue>';
		echo '<featureValue>';
			echo '<count>1</count>';
			echo '<listingFeatureName>SPORTS_SAILING</listingFeatureName>';
		echo '</featureValue>';
		echo '<featureValue>';
			echo '<count>1</count>';
			echo '<listingFeatureName>CAR_RECOMMENDED</listingFeatureName>';
		echo '</featureValue>';
	echo '</featureValues>';
	echo '<location>';
		echo '<address>';
			echo '<addressLine1>3195 Main St.</addressLine1>';
			echo '<addressLine2>Historic Rte 6A - Olde Kings Highway</addressLine2>';
			echo '<city>Barnstable</city>';
			echo '<stateOrProvince>MA</stateOrProvince>';
			echo '<country>US</country>';
			echo '<postalCode>02630</postalCode>';
		echo '</address>';
		echo '<description>';
		echo '	<texts>';
				echo '<text locale="en">';
					echo '<textValue>Barnstable Village is located along Historic RTE 6A - the scenic road of Cape Cod known as Old Kings Highway.</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</description>';
		echo '<geoCode>';
			echo '<latLng>';
			echo '	<latitude>41.70019</latitude>';
			echo '	<longitude>-70.304107</longitude>';
			echo '</latLng>';
		echo '</geoCode>';
		echo '<nearestPlaces>';
			echo '<nearestPlace placeType="AIRPORT">';
				echo '<distance>5.0</distance>';
				echo '<distanceUnit>MILES</distanceUnit>';
				echo '<name>';
					echo '<texts>';
						echo '<text locale="en">';
							echo '<textValue>Barnstable Airport 5mi - Boston 65 mi</textValue>';
						echo '</text>';
					echo '</texts>';
				echo '</name>';
			echo '</nearestPlace>';
			echo '<nearestPlace placeType="BEACH">';
				echo '<distance>2.0</distance>';
				echo '<distanceUnit>MINUTES</distanceUnit>';
				echo '<name>';
					echo '<texts>';
						echo '<text locale="en">';
							echo '<textValue>Sandy Neck Beach</textValue>';
						echo '</text>';
					echo '</texts>';
				echo '</name>';
			echo '</nearestPlace>';
		echo '</nearestPlaces>';
		echo '<otherActivities>';
			echo '<texts>';
				echo '<text locale="en">';
					echo '<textValue>Relax in the Barnstable Day Spa located next door to the property.</textValue>';
				echo '</text>';
			echo '</texts>';
		echo '</otherActivities>';
		echo '<showExactLocation>true</showExactLocation>';
	echo '</location>';
	echo '<images>';
		echo '<image>';
			echo '<externalId>img123</externalId>';
			echo '<title>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>The Main House</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</title>';
			echo '<uri>http://misite.com/image?id=img123</uri>';
		echo '</image>';
	echo '</images>';
	echo '<units>';
		echo '<unit>';
			echo '<externalId>501a</externalId>';
			echo '<active>true</active>';
			echo '<area>3600</area>';
			echo '<areaUnit>SQUARE_FEET</areaUnit>';
			echo '<bathroomDetails>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>Very large Master Bath</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</bathroomDetails>';
			echo '<bathrooms>';
				echo '<bathroom>';
					echo '<amenities>';
						echo '<amenity>';
							echo '<count>1</count>';
							echo '<bathroomFeatureName>AMENITY_TOILET</bathroomFeatureName>';
						echo '</amenity>';
						echo '<amenity>';
							echo '<count>1</count>';
							echo '<bathroomFeatureName>AMENITY_JETTED_TUB</bathroomFeatureName>';
						echo '</amenity>';
					echo '</amenities>';
					echo '<name>';
						echo '<texts>';
							echo '<text locale="en">';
								echo '<textValue>Bathroom 1</textValue>';
							echo '</text>';
						echo '</texts>';
					echo '</name>';
					echo '<note>';
						echo '<texts>';
							echo '<text locale="en">';
								echo '<textValue>Master Suite</textValue>';
							echo '</text>';
						echo '</texts>';
					echo '</note>';
					echo '<roomSubType>FULL_BATH</roomSubType>';
				echo '</bathroom>';
			echo '</bathrooms>';
			echo '<bedroomDetails>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>Master Suite with Jacuzzi tub.  Formal Suite with garden view and a fireplace.</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</bedroomDetails>';
			echo '<bedrooms>';
				echo '<bedroom>';
					echo '<amenities>';
						echo '<amenity>';
							echo '<count>1</count>';
							echo '<bedroomFeatureName>AMENITY_QUEEN</bedroomFeatureName>';
						echo '</amenity>';
						echo '<amenity>';
							echo '<count>1</count>';
							echo '<bedroomFeatureName>AMENITY_SLEEP_SOFA</bedroomFeatureName>';
						echo '</amenity>';
					echo '</amenities>';
					echo '<name>';
						echo '<texts>';
							echo '<text locale="en">';
								echo '<textValue>Bedroom 1</textValue>';
							echo '</text>';
						echo '</texts>';
					echo '</name>';
					echo '<note>';
						echo '<texts>';
							echo '<text locale="en">';
								echo '<textValue>Master Suite</textValue>';
							echo '</text>';
						echo '</texts>';
					echo '</note>';
					echo '<roomSubType>BEDROOM</roomSubType>';
				echo '</bedroom>';
			echo '</bedrooms>';
			echo '<description>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>Beautiful views surround the unit.</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</description>';
			echo '<diningSeating>10</diningSeating>';
			echo '<featuresDescription>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>This charming home will meet all your expectations.</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</featuresDescription>';
			echo '<featureValues>';
				echo '<featureValue>';
					echo '<count>1</count>';
					echo '<unitFeatureName>AMENITIES_GARAGE</unitFeatureName>';
				echo '</featureValue>';
				echo '<featureValue>';
					echo '<count>1</count>';
					echo '<unitFeatureName>AMENITIES_INTERNET</unitFeatureName>';
				echo '</featureValue>';
			echo '</featureValues>';
			echo '<images>';
				echo '<image>';
					echo '<externalId>unitImage1</externalId>';
					echo '<uri>http://misite.com/image1</uri>';
				echo '</image>';
				echo '<image>';
					echo '<externalId>unitImage2</externalId>';
					echo '<uri>http://misite.com/image2</uri>';
				echo '</image>';
			echo '</images>';
			echo '<loungeSeating>10</loungeSeating>';
			echo '<propertyType>PROPERTY_TYPE_HOUSE</propertyType>';
			echo '<registrationNumber>123456</registrationNumber>';
			echo '<representedUnits>1</representedUnits>';
			echo '<unitMonetaryInformation>';
				echo '<currency>USD</currency>';
			echo '</unitMonetaryInformation>';
			echo '<unitName>';
				echo '<texts>';
					echo '<text locale="en">';
						echo '<textValue>unit_1234</textValue>';
					echo '</text>';
				echo '</texts>';
			echo '</unitName>';
		echo '</unit>';
	echo '</units>';
echo '</listing>';