<?php
header("Content-type: text/xml");
require_once('../../booking/init.php');

//$_GET['property_id']='22';
 if ($_GET['property_id']){ }
 $link= new getQueries();
 $bookings=$link->availability_flipkey($_GET['property_id']);
 
echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<!--Sample XML file generated by XMLSpy v2016 rel. 2 sp1 (http://www.altova.com)-->';
echo '<advertiserListingContentIndex>';
	echo '<documentVersion>4.1</documentVersion>';
	echo '<advertiser>';
		echo '<assignedId>advertiser_1</assignedId>';
		echo '<listingContentIndexEntry>';
			echo '<listingExternalId>501</listingExternalId>';
			echo '<active>true</active>';
			echo '<lastUpdatedDate>2016-09-02T10:23:35Z</lastUpdatedDate>';
			echo '<listingUrl>http://www.site.com/ha/listing?id=501</listingUrl>';
		echo '</listingContentIndexEntry>';
		echo '<listingContentIndexEntry>';
			echo '<listingExternalId>502</listingExternalId>';
			echo '<active>true</active>';
			echo '<lastUpdatedDate>2016-09-03T13:30:35Z</lastUpdatedDate>';
			echo '<listingUrl>http://www.site.com/ha/listing?id=502</listingUrl>';
		echo '</listingContentIndexEntry>';
		echo '<listingContentIndexEntry>';
			echo '<listingExternalId>503</listingExternalId>';
			echo '<active>false</active>';
			echo '<lastUpdatedDate>2016-09-02T18:00:35Z</lastUpdatedDate>';
			echo '<listingUrl>http://www.site.com/ha/listing?id=503</listingUrl>';
		echo '</listingContentIndexEntry>';
	echo '</advertiser>';
echo '</advertiserListingContentIndex>';