
(function(){PAYPAL.namespace("love");var Y=YAHOO.util.Dom,YEV=YAHOO.util.Event,emailArray=new Array();var purchaseRadio=Y.getElementsByClassName("purchase","","SMTtabs"),personalRadio=Y.getElementsByClassName("personal","","SMTtabs");PAYPAL.love.p2p={init:function(){this.initHomePage();this.initRMHomePage();this.initRMReviewPage();this.initCurrencyConversion();var recentSelect=Y.get('recent_select');if(Y.get("sendToAutoSuggest")&&recentSelect){var Auto=new PAYPAL.widget.AutoComplete(Y.get('email'),recentSelect,{deepSearch:true});}
if(Y.get("ismForm")){Y.addClass(['smtNoJSMessage','smtPersonal','smtEbayOptions'],'hide');Y.addClass('submit','relocateButton');Y.addClass('descbttn','descPosition');this.initTabs();YEV.addListener("PurchaseEBayItem","click",function(e){PAYPAL.love.p2p.eBayOptions('Show')});YEV.addListener(["PurchaseAuctionGoods","PurchaseOther","PurchaseGoods","PersonalOther","PurchaseServices","PurchaseCashAdvance","PersonalGift","PersonalLivingExpense","PersonalEntertainment","PersonalCashAdvance"],"click",function(e){PAYPAL.love.p2p.eBayOptions('Hide');PAYPAL.love.p2p.eBayCheckout('Hide');});YEV.addListener("RetireSMEI","click",function(e){PAYPAL.love.p2p.eBayCheckout('Show');});YEV.addListener(purchaseRadio,"click",function(e){personalRadio[0].checked=true;personalRadio[0].checked=false});YEV.addListener(personalRadio,"click",function(e){purchaseRadio[0].checked=true;purchaseRadio[0].checked=false;});}},captureEnterKey:function(e){var keyPressed=e.charCode||e.keyCode;var target=e.target||e.srcElement;var validElements=/INPUT/i;var textElements=/TEXT/i;if((e.keyCode==13)&&(validElements.test(target.nodeName))&&(textElements.test(target.type))){btns=YUD.getElementsByClassName('defaultSubmit');if(btns[0]){YUE.preventDefault(e);if(target.id=="email"){if(YUD.get("recentContacts")){var resultElt=Y.getElementsByClassName("acResults");if(!Y.hasClass(resultElt[resultElt.length-1],"accessAid")){if(target.value==""){btns[0].click();}else{var resultListElts=Y.getFirstChild(resultElt[resultElt.length-1]).getElementsByTagName('li');if(resultListElts.length==1){if(Y.hasClass(resultListElts,"active")=="true"){return false;}else{btns[0].click();}}else{return false;}}}else{btns[0].click();}}else{btns[0].click();}
return true;}else{btns[0].click();return true;}}}},initHomePage:function(){var updateCurrencyLink=Y.getElementsByClassName("currencyUpdater","a");if(updateCurrencyLink[0]){updateCurrencyLink[0].style.display='inline';}
var amount=Y.get("amount")||Y.get("uome_amount");var chooseCurrency=Y.get("amount_ccode")||Y.get("uome_amount_ccode");if(amount.value==""){Y.setStyle("currencyEquivalent","display","none");}
if(Y.get("emailNameBlock")){this.getVerified();YEV.addListener('email',"blur",this.getVerified);}
if(Y.get("recentContacts")){Y.setStyle("recentContacts","display","none");}
if(Y.get("sendToAutoSuggest"))
{if(Y.hasClass(Y.get("sendToAutoSuggest").children[0],"error"))
this.setPaddingOnError();}
else if(Y.get("newSendToAutoSuggest"))
{if(Y.hasClass(Y.get("newSendToAutoSuggest").children[0],"error"))
this.setPaddingOnError();}
if(Y.get("smtPurchaseTabLink")){YUE.addListener([Y.get("smtPurchaseTabLink"),Y.get("smtPersonalTabLink")],"keydown",this.tabNavigation);Y.get("smtPersonalTabLink").setAttribute("tabIndex","-1");}
Y.setStyle("updateCurrency","display","none");YEV.addListener(updateCurrencyLink,"click",this.convert_onClick_href);YEV.addListener([amount,chooseCurrency],"change",this.convert_onClick);YEV.addListener('ismForm','keypress',PAYPAL.love.p2p.captureEnterKey);YEV.addListener('ismForm','submit',this.beforeSubmit);},tabNavigation:function(e)
{var a=YUE.getCharCode(e);var KEY_LEFT=37,KEY_RIGHT=39,KEY_UP=38,KEY_DOWN=40;switch(a){case KEY_LEFT:case KEY_UP:Y.get("smtPurchaseTabLink").focus();PAYPAL.love.p2p.switchPurchaseOn(e);Y.get("smtPersonalTabLink").setAttribute("tabIndex","-1");Y.get("smtPurchaseTabLink").setAttribute("tabIndex","0");break;case KEY_RIGHT:case KEY_DOWN:Y.get("smtPersonalTabLink").focus();PAYPAL.love.p2p.switchPersonalOn(e);Y.get("smtPurchaseTabLink").setAttribute("tabIndex","-1");Y.get("smtPersonalTabLink").setAttribute("tabIndex","0");break;}},beforeSubmit:function(){if(Y.get("dynamicExe")&&typeof(data.contactdetails)!="undefined"){PAYPAL.love.p2p.getP2PUpdated();}},setPaddingOnError:function(){if(Y.get("emailNamePreContent")){Y.addClass('emailNamePreContent','smErrorPadding');}
Y.addClass('emailBlockLoading','smErrorPadding');Y.addClass('emailNameBlock','smErrorPadding');Y.addClass('emailError','smErrorPadding');},getVerified:function(){setTimeout(function(){var email=Y.get("email").value;var emailPattern=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;var url="cgi-bin/webscr?cmd=_verify_sendmoney_recipient&email_id="+escape(email);if((email!="")&&(emailPattern.test(email))){if(Y.get("emailPrevValue").value==email){return;}
if(Y.get("emailNamePreContent")){Y.setStyle("emailNamePreContent","display","none");}
Y.setStyle("emailBlockLoading","display","inline");Y.setStyle("emailNameBlock","display","none");Y.setStyle("emailNameContent","display","none");Y.setStyle("emailError","display","none");PAYPAL.util.Connect.send(url,{callback:PAYPAL.love.p2p.getEmailVerification});Y.get("emailPrevValue").value=email;}
else{Y.get("emailPrevValue").value="";if(email.indexOf("or select a recent contact")>-1){Y.get("email").value="";}
if(Y.get("emailNamePreContent")){Y.setStyle("emailNamePreContent","display","none");}
Y.setStyle("emailBlockLoading","display","none");Y.setStyle("emailNameBlock","display","none");Y.setStyle("emailNameContent","display","none");Y.setStyle("emailError","display","none");}
PAYPAL.love.p2p.fixHeight();},500);},getP2PUpdated:function(){if(Y.get('email').value!="")
{if(Y.get('email').nextSibling.name.indexOf("email")!=-1){Y.get('email').value=Y.get('email').nextSibling.value;var p2pEmailId;var p2pContactId;for(var i=0;i<data.contactdetails.length;i++){if(Y.get('email').value==data.contactdetails[i].email||Y.get('email').value==data.contactdetails[i].result){p2pEmailId=data.contactdetails[i].email;p2pContactId=data.contactdetails[i].contact_id;if(data.contactdetails[i].truncated!=undefined)
Y.get('email').value=Y.get('email').value.slice(0,Y.get('email').value.length-1);break;}}
if(p2pEmailId!=undefined){YUD.get("email").value=p2pEmailId;document.getElementsByName("email")[0].value=p2pEmailId;document.getElementsByName("contact_id")[0].value=p2pContactId;}
else{document.getElementsByName("contact_id")[0].value="";}}}},initRMHomePage:function(){YEV.addListener("recent_select",'change',function(e){PAYPAL.love.p2p.pushEmail(e)});},initRMReviewPage:function(){YEV.addListener("note","keyup",function(e){PAYPAL.love.p2p.counterKey(e)});YEV.addListener("note","keydown",function(e){PAYPAL.love.p2p.counterKey(e)});},initCurrencyConversion:function(){var currencyIn=Y.get("amount_ccode")||Y.get("uome_amount_ccode");var currencyInValue=currencyIn.value;var currencyOut=Y.get("currency_out").value;(currencyOut!=currencyInValue)?Y.setStyle("currencyEquivalent","display","block"):Y.setStyle("currencyEquivalent","display","none");},textCounter:function(field,cntfield,maxlimit){(field.value.length>maxlimit)?field.value=field.value.substring(0,maxlimit):cntfield.innerHTML=field.value.length;},counterKey:function(e){this.textCounter(document.Confirm.note,Y.get("numChars"),300);},pushEmail:function(e){var email_object=Y.get("recent_select");if(email_object.selectedIndex==0){return;}
var form_field=Y.get("uome_recipients");var duplicate=false;for(var i=0,j=emailArray.length;i<j;i++){if(emailArray[i]==email_object.selectedIndex){duplicate=true;break;}}
if(duplicate==false){(form_field.value=='')?form_field.value=email_object.value:form_field.value=form_field.value+', '+email_object.value;emailArray[emailArray.length]=email_object.selectedIndex;}},getUpdatedCurrency:function(e){YEV.preventDefault(e);},getTagContents:function(sTag,sString){var oRex=new RegExp("<"+sTag+">(.{1,})<");var bMatch=oRex.exec(sString);return(bMatch!==null)?bMatch[1]:null;},getEmailVerification:function(json,request){var sVerifyStatus=PAYPAL.love.p2p.getTagContents("FullName",request.responseText);var sUnVerifyStatus=request.responseText.indexOf("Unverified");var oMessage=Y.get("emailNameBlock");var oMessageContent=Y.get("emailNameContent");if(sVerifyStatus!==null){oMessage.innerHTML=sVerifyStatus.replace(/&apos;/g,"'");Y.setStyle("emailError","display","none");if(Y.get("emailNamePreContent")){Y.setStyle("emailNamePreContent","display","inline");}
Y.setStyle("emailNameBlock","display","inline");Y.setStyle("emailNameContent","display","inline");}
else if(sUnVerifyStatus>-1){if(Y.get("emailNamePreContent")){Y.setStyle("emailNamePreContent","display","none");}
Y.setStyle("emailNameBlock","display","none");Y.setStyle("emailNameContent","display","none");Y.setStyle("emailError","display","block");}
else
{if(Y.get("emailNamePreContent")){Y.setStyle("emailNamePreContent","display","none");}
Y.get("emailPrevValue").value="";Y.setStyle("emailNameBlock","display","none");Y.setStyle("emailNameContent","display","none");Y.setStyle("emailError","display","none");}
Y.setStyle("emailBlockLoading","display","none");PAYPAL.love.p2p.fixHeight();},convert_setAmount:function(json,request){var sAmount=PAYPAL.love.p2p.getTagContents("amount_out_formatted",request.responseText);var oMessage=Y.get("conversion");var prependCurrencyAmtEl=Y.get("prependCurrencyAmt");if(sAmount!==null){var prepend=(prependCurrencyAmtEl)?prependCurrencyAmtEl.innerHTML:"";oMessage.innerHTML=prepend+sAmount;Y.setStyle("conversionError","display","none");Y.setStyle("conversionInProgress","display","none");Y.setStyle("currencyEquivalent","display","block");}else{Y.setStyle("conversionInProgress","display","none");Y.setStyle("conversionError","display","block");}
PAYPAL.love.p2p.fixHeight();},convert_onClick_href:function(e){YEV.preventDefault(e);PAYPAL.love.p2p.convert_onClick(e);},convert_onClick:function(e){var amount=Y.get("amount")||Y.get("uome_amount");var amountOut=(amount)?amount.value:"";var currencyIn=Y.get("amount_ccode")||Y.get("uome_amount_ccode");if(currencyIn.selectedIndex){var currencyInValue=currencyIn.options[currencyIn.selectedIndex].value;}else{var currencyInValue=currencyIn.value;}
var currencyOut=Y.get("currency_out").value;var url="cgi-bin/webscr?cmd=_cconversion&amount_in="+escape(amountOut)+"&currency_in="+escape(currencyInValue)+"&currency_out="+escape(currencyOut);if(currencyOut!=currencyInValue){PAYPAL.util.Connect.send(url,{callback:PAYPAL.love.p2p.convert_setAmount});Y.setStyle("currencyEquivalent","display","none");Y.setStyle("conversionInProgress","display","block");}else{Y.setStyle("currencyEquivalent","display","none");Y.setStyle("conversionError","display","none");Y.setStyle("conversionInProgress","display","none");}},initTabs:function(){try{var retireSMEI=Y.get("RetireSMEI")
if(retireSMEI&&retireSMEI.checked)this.eBayCheckout('Show');}catch(e){}
try{var purEbay=Y.get("PurchaseEBayItem")
if(purEbay&&purEbay.checked)this.eBayOptions('Show');}catch(e){}
if(Y.get("smtPersonal")){Y.replaceClass('SMTtabs',"noJS","yesJS");Y.addClass('SendMoney','MainFieldSetHeight');YEV.addListener("smtPersonalTabLink","click",function(e){PAYPAL.love.p2p.switchPersonalOn(e)});YEV.addListener("smtPurchaseTabLink","click",function(e){PAYPAL.love.p2p.switchPurchaseOn(e)});var showTabsPersonal=Y.get("showTabsPersonal");if(showTabsPersonal&&!Y.get("showTabsPurchase")){this.switchPersonalOn();}
if(!showTabsPersonal){this.switchPurchaseOn();}}else{Y.replaceClass('SMTtabs',"noTabsNoJS","noTabsYesJS");Y.addClass('SendMoney','MainFieldSetNoTabsHeight');PAYPAL.love.p2p.fixHeight();}},getRadioButtonValue:function(radio){for(var i=0;i<radio.length;i++){if(radio[i].checked){return radio[i].value}}
return'';},purchasePersonalCheck:function(checkID){var selected='';if(checkID==="smtPurchaseTabLink"){selected=this.getRadioButtonValue(purchaseRadio);if(selected=='')purchaseRadio[0].checked=true;personalRadio[0].checked=true;personalRadio[0].checked=false;}
if(checkID==="smtPersonalTabLink"){selected=this.getRadioButtonValue(personalRadio);if(selected=='')personalRadio[0].checked=true;purchaseRadio[0].checked=true;purchaseRadio[0].checked=false;}},eBayCheckout:function(disp){if(disp=='Hide'){Y.get("email").removeAttribute("disabled");Y.get("amount").removeAttribute("disabled");Y.get("amount_ccode").removeAttribute("disabled");Y.removeClass('submit','hide');Y.removeClass('descbttn','hide');Y.addClass('smtEbayOptions','hide');}
if(disp=='Show'){Y.get("email").setAttribute("disabled",true);Y.get("amount").setAttribute("disabled",true);Y.get("amount_ccode").setAttribute("disabled",true);Y.addClass('submit','hide');Y.addClass('descbttn','hide');Y.removeClass('smtEbayOptions','hide');}
this.fixHeight();},eBayOptions:function(disp){(disp=='Hide')?Y.addClass('smtEbayOptions','hide'):'';(disp=='Show')?Y.removeClass('smtEbayOptions','hide'):'';this.fixHeight();},fixHeight:function(){var mainFieldset=Y.get("SendMoney");var tabsFieldset=Y.get("smtPurchase");if(!mainFieldset||!tabsFieldset){return;}
var browser=navigator.appName;var heightExtra;var tabsHeight=0;var whichTab;tabsFieldset.style.height="auto";if(browser=="Microsoft Internet Explorer"){heightExtra=21;tabsMinus=10;}else{heightExtra=25;tabsMinus=10;}
if(Y.hasClass('smtPersonalTabLink','smtMainTab')){tabsHeight=Y.get("smtPersonal").offsetHeight;}else if(Y.hasClass('smtPurchaseTabLink','smtMainTab')){if(Y.get("smtEbayOptions")&&!Y.hasClass('smtEbayOptions','hide')){if(Y.get("PurchaseServices")){var serviceRef=Y.get("PurchaseServices").offsetTop;var heightEbay;if(browser!="Microsoft Internet Explorer"){heightEbay=23;if(Y.get("smtEbayOptions")){Y.get("smtEbayOptions").style.top=heightEbay+serviceRef+"px";}}else{var splitArray=navigator.appVersion.split("MSIE ");var version=parseFloat(splitArray[1]);heightEbay=Y.get("SMTtabs").offsetTop;if(version==7){if(Y.get('smtPurchaseHeaderDesc')){heightEbay+=-11;}else{heightEbay+=-50;}}else if(version==6){if(Y.get('smtPurchaseHeaderDesc')){heightEbay+=13;}else{heightEbay+=-40;}}else{heightEbay+=-100;}}}
Y.get("smtPurchase").style.padding=(Y.hasClass(document.body,'rtl'))?"10px 14px 12px 10px":"10px 10px 12px 14px";tabsHeight=Y.get("smtEbayOptions").offsetHeight+tabsFieldset.offsetHeight;tabsFieldset.style.height=tabsHeight-tabsMinus+"px";heightExtra+=12;}else{Y.get("smtPurchase").style.padding=(Y.hasClass(document.body,'rtl'))?"10px 14px 24px 10px":"10px 10px 24px 14px";tabsHeight=tabsFieldset.offsetHeight;}}else{if(Y.get("smtEbayOptions")&&!Y.hasClass('smtEbayOptions','hide')){tabsHeight=Y.get("smtEbayOptions").offsetHeight+tabsFieldset.offsetHeight;tabsFieldset.style.height=tabsHeight-tabsMinus+"px";}else{tabsHeight=tabsFieldset.offsetHeight;}
var serviceRef=Y.get("PurchaseServices").offsetTop;var heightEbay;if(browser=="Microsoft Internet Explorer"){heightEbay=Y.get("SMTtabs").offsetTop;var browser_IE=navigator.userAgent.toLowerCase().indexOf('msie 6');var browser_IE7=navigator.userAgent.toLowerCase().indexOf('msie 7');if(browser_IE!=-1){heightEbay+=93;}else if(browser_IE7!=-1){heightEbay+=83;}else{heightEbay=23;}}else{heightEbay=23;}
if(Y.get("smtEbayOptions")){Y.get("smtEbayOptions").style.top=heightEbay+serviceRef+"px";}
heightExtra+=13;tabsHeight=0;}
mainFieldset.style.height="auto";mainFieldset.style.height=tabsHeight+mainFieldset.offsetHeight+heightExtra+"px";},switchPersonalOn:function(e){if(e)YEV.preventDefault(e);this.eBayCheckout('Hide');Y.replaceClass('smtPurchaseTabLink','smtMainTab','smtSubTab');Y.replaceClass('smtPurchaseTabLink','smtMainImages','smtSubRightImages');(Y.hasClass(document.body,'rtl'))?Y.addClass('smtPurchaseTabLink','smtSubLeftBorder'):Y.addClass('smtPurchaseTabLink','smtSubRightBorder');Y.replaceClass('smtPurchaseTab','smtMainPurchaseMargin','smtSubPurchaseMargin');Y.replaceClass('smtPersonalTabLink','smtSubTab','smtMainTab');Y.replaceClass('smtPersonalTabLink','smtSubImages','smtMainImages');Y.replaceClass('smtPersonalTab','smtSubPersonalMargin','smtMainPersonalMargin');Y.addClass('smtPurchase','hide');Y.removeClass('smtPersonal','hide');this.purchasePersonalCheck("smtPersonalTabLink");var personalWidth=Y.get("smtPersonalTab").offsetWidth;var purchaseWidth=Y.get("smtPurchaseTab").offsetWidth;if(YAHOO.env.ua.ie==8){Y.setStyle(Y.get('smtPurchaseTabLink'),"margin-top","0px");Y.setStyle(Y.get('smtPersonalTabLink'),"margin-top","2px");}
if((navigator.userAgent.toLowerCase().indexOf('safari')>-1)||(navigator.userAgent.toLowerCase().indexOf('chrome')>-1)){Y.setStyle(Y.get('smtPurchaseTabLink'),"margin-top","0px");Y.setStyle(Y.get('smtPersonalTabLink'),"margin-top","3px");}
this.fixHeight();},switchPurchaseOn:function(e){if(e)YEV.preventDefault(e);Y.removeClass('smtPurchase','hide');Y.addClass('smtPersonal','hide');Y.replaceClass('smtPersonalTabLink','smtMainTab','smtSubTab');Y.replaceClass('smtPersonalTabLink','smtMainImages','smtSubImages');Y.replaceClass('smtPersonalTab','smtMainPersonalMargin','smtSubPersonalMargin');Y.replaceClass('smtPurchaseTab','smtSubPurchaseMargin','smtMainPurchaseMargin');Y.replaceClass('smtPurchaseTabLink','smtSubTab','smtMainTab');Y.replaceClass('smtPurchaseTabLink','smtSubRightImages','smtMainImages');(Y.hasClass(document.body,'rtl'))?Y.removeClass('smtPurchaseTabLink','smtSubLeftBorder'):Y.removeClass('smtPurchaseTabLink','smtSubRightBorder');this.purchasePersonalCheck('smtPurchaseTabLink');var showEbayForm=0;try{var RetireSMEI=Y.get("RetireSMEI");if(RetireSMEI&&RetireSMEI.checked)showEbayForm=1;}catch(e){}
try{var PurchaseEBayItem=Y.get("PurchaseEBayItem")
if(PurchaseEBayItem&&PurchaseEBayItem.checked)showEbayForm=1;}catch(e){}
if(showEbayForm!=1){Y.removeClass('smtEbayOptions','hide');Y.addClass('smtEbayOptions','hide');}
var purchaseWidth=Y.get("smtPurchaseTab").offsetWidth;if(YAHOO.env.ua.ie==8){Y.setStyle(Y.get('smtPurchaseTabLink'),"margin-top","2px");Y.setStyle(Y.get('smtPersonalTabLink'),"margin-top","0px");}
if((navigator.userAgent.toLowerCase().indexOf('safari')>-1)||(navigator.userAgent.toLowerCase().indexOf('chrome')>-1)){Y.setStyle(Y.get('smtPurchaseTabLink'),"margin-top","2px");Y.setStyle(Y.get('smtPersonalTabLink'),"margin-top","0px");}
this.fixHeight();}};YEV.addListener(window,'load',PAYPAL.love.p2p.init,PAYPAL.love.p2p,true);})();